<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Portfolio.Core\Portfolio.Core.csproj" />
    <ProjectReference Include="..\Portfolio.Kis\Portfolio.Kis.csproj" />
    <ProjectReference Include="..\Portfolio.Data\Portfolio.Data.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <UserSecretsId>54cc3b55-4d35-4733-b222-3fa021e5fa41</UserSecretsId>
  </PropertyGroup>

</Project>
