namespace Portfolio.Web.Services;

// 영어 번역표 (F-12). 키는 화면에 쓰는 한국어 원문 그대로다.
// 문구를 새로 넣거나 고치면 여기에도 같은 원문으로 넣어야 한다 (빠지면 LocalizationTests가 알려 준다).
public sealed partial class Loc
{
    private static readonly Dictionary<string, string> En = new(StringComparer.Ordinal)
    {
        // 공통
        ["포트폴리오"] = "Portfolio",
        ["포트폴리오 대시보드"] = "Portfolio Dashboard",
        ["주 메뉴"] = "Main menu",
        ["대시보드"] = "Dashboard",
        ["보유 종목"] = "Holdings",
        ["리밸런싱"] = "Rebalance",
        ["그룹 관리"] = "Groups",
        ["설정"] = "Settings",
        ["계좌"] = "Account",
        ["불러오는 중…"] = "Loading…",
        ["저장"] = "Save",
        ["취소"] = "Cancel",
        ["삭제"] = "Delete",
        ["수정"] = "Edit",
        ["추가"] = "Add",
        ["편집"] = "Edit",
        ["닫기"] = "Close",
        ["아니요"] = "No",
        ["보기"] = "View",
        ["작업"] = "Actions",
        ["위로"] = "Move up",
        ["아래로"] = "Move down",
        ["이름"] = "Name",
        ["색상"] = "Color",
        ["순서"] = "Order",
        ["합계"] = "Total",
        ["차이"] = "Gap",
        ["그룹"] = "Group",
        ["종목명"] = "Name",
        ["수량"] = "Qty",
        ["평균매입단가"] = "Avg cost",
        ["현재가"] = "Price",
        ["평가금액"] = "Value",
        ["비중"] = "Weight",
        ["손익률"] = "Return",
        ["수정일"] = "Updated",
        ["금액"] = "Amount",
        ["구분"] = "Side",
        ["주수"] = "Shares",
        ["목표"] = "Target",
        ["현재"] = "Now",
        ["원"] = "KRW",
        ["개"] = "",
        ["초"] = "sec",
        ["미분류"] = "Unclassified",
        ["현금"] = "Cash",
        ["기타"] = "Others",
        ["매도"] = "Sell",
        ["매수"] = "Buy",
        ["유지"] = "Hold",
        ["{0} 매도"] = "Sell {0}",
        ["{0} 매수"] = "Buy {0}",

        // 상단 바·시세 상태
        ["총 평가금액"] = "Total value",
        ["보유 종목을 추가하세요"] = "Add your holdings to begin",
        ["현재가를 받으면 손익이 계산됩니다"] = "P/L appears once prices arrive",
        ["장중"] = "Market open",
        ["장 마감"] = "Market closed",
        ["{0} 시세 갱신"] = "prices as of {0}",
        ["{0} 갱신"] = "as of {0}",
        ["시세 없음"] = "No price",
        ["시세 지연"] = "Stale price",

        // 시장 지표
        ["시장 지표"] = "Market indicators",
        ["코스피"] = "KOSPI",
        ["코스닥"] = "KOSDAQ",
        ["나스닥"] = "NASDAQ",
        ["원/달러 환율"] = "USD/KRW",
        ["받아오는 중"] = "Loading",
        ["상승"] = "Up",
        ["하락"] = "Down",
        ["보합"] = "Unchanged",
        ["KIS 앱키를 넣으면 코스피·코스닥·S&P 500·나스닥·원/달러 환율이 여기에 표시됩니다."] =
            "KOSPI, KOSDAQ, S&P 500, NASDAQ and USD/KRW appear here once a KIS app key is set.",

        // 시세 안내
        ["현재가를 받아오지 못하고 있습니다."] = "Prices are not being received.",
        ["KIS 앱키가 설정되지 않았습니다. 그동안 시세가 없는 종목은 <strong>매입금액</strong>으로 계산해 보여 주고, 손익은 계산하지 않습니다."] =
            "No KIS app key is set. Until then, holdings without a price are shown at <strong>cost</strong> and P/L is not calculated.",
        ["키를 발급받으면 아래 파일의 AppKey·AppSecret에 넣고 앱을 다시 켜세요:"] =
            "Once you have a key, put it in AppKey and AppSecret in the file below and restart the app:",
        ["{0}개 종목의 현재가를 아직 받지 못했습니다."] = "Prices for {0} holding(s) have not arrived yet.",
        ["해당 종목은 <strong>매입금액</strong>으로 계산해 보여 주고, 손익은 계산하지 않습니다. 장중에는 다음 갱신 때 반영됩니다."] =
            "They are shown at <strong>cost</strong> and P/L is not calculated. During market hours they update on the next refresh.",
        ["{0}개 종목은 시세 갱신에 실패했습니다."] = "The price refresh failed for {0} holding(s).",
        ["마지막으로 받은 가격으로 표시하고 있습니다."] = "The last received price is shown.",

        // 대시보드
        ["보유 종목을 추가하면 시작됩니다"] = "Add your holdings to get started",
        ["삼성증권 잔고 화면의 종목·수량·평균매입단가를 옮겨 적으면, 총 평가금액과 종목·그룹별 비중을 여기서 볼 수 있습니다."] =
            "Copy each holding's quantity and average cost from your brokerage balance screen to see the total value and the weights by holding and group here.",
        ["<strong>보유 종목</strong>에서 종목을 검색해 수량과 평균매입단가를 입력합니다."] =
            "In <strong>Holdings</strong>, search for a stock and enter its quantity and average cost.",
        ["<strong>그룹 관리</strong>에서 주식·채권·배당의 목표 비중을 정합니다."] =
            "In <strong>Groups</strong>, set the target weight of each group.",
        ["<strong>추가매수 계산</strong>에서 투입 금액을 넣으면 살 종목과 주수가 나옵니다."] =
            "In <strong>Buy plan</strong>, enter an amount to see which stocks to buy and how many shares.",
        ["보유 종목 추가하기"] = "Add holdings",
        [" · 보유수량 최종 수정 {0}"] = " · quantities last edited {0}",
        ["추가매수 계산하기"] = "Plan a buy",
        ["그룹이 지정되지 않은 종목이 {0}개 있습니다. 미분류 종목은 목표 비중 계산에서 0%로 취급됩니다."] =
            "{0} holding(s) have no group. Unclassified holdings count as 0% in the target calculation.",
        ["그룹 지정하기"] = "Assign groups",
        ["요약"] = "Summary",
        ["매입금액"] = "Cost",
        ["수량 × 평균매입단가"] = "Quantity × average cost",
        ["평가손익"] = "Unrealized P/L",
        ["현재가를 받으면 계산됩니다"] = "Calculated once prices arrive",
        [" · 시세 있는 {0}개 종목 기준"] = " · based on {0} priced holding(s)",
        ["미분류 {0}개 · 시세 지연 {1}개"] = "{0} unclassified · {1} stale",
        [" · 시세 없음 {0}개"] = " · {0} without price",
        ["예수금 포함"] = "Cash included",
        ["예수금 제외"] = "Cash excluded",
        [" · {0}개 종목은 매입금액 기준"] = " · {0} holding(s) at cost",
        ["그룹별 비중"] = "Weight by group",
        ["항목을 누르면 아래 표에서 그 그룹만 봅니다."] = "Tap an item to show only that group in the table below.",
        ["{0}개 그룹"] = "{0} groups",
        ["그룹별 비중 도넛 차트"] = "Donut chart of weight by group",
        ["종목별 비중"] = "Weight by holding",
        ["항목을 누르면 아래 표에서 그 종목만 봅니다."] = "Tap an item to show only that holding in the table below.",
        ["{0}개 종목"] = "{0} holdings",
        ["종목별 비중 도넛 차트"] = "Donut chart of weight by holding",
        ["목표 대비"] = "Versus target",
        ["막대 = 현재 비중, "] = "Bar = current weight, ",
        ["세로선 = 목표"] = "line = target",
        [" 비중"] = " weight",
        [" 초과"] = " over",
        [" 부족"] = " under",
        ["목표 도달"] = "On target",
        ["{0} 만 보기 · 해제"] = "Showing {0} only · clear",
        ["편집하기"] = "Edit",
        ["해당하는 종목이 없습니다."] = "No matching holdings.",
        ["비중은 소수점 1자리 반올림으로, 합계가 100.0%가 아닐 수 있습니다. 열 제목을 누르면 정렬됩니다."] =
            "Weights are rounded to one decimal place, so they may not add up to 100.0%. Click a column header to sort.",

        // 보유 종목 표
        ["현재가를 아직 받지 못했습니다"] = "No price has been received yet",
        ["최근 시세 갱신에 실패해 마지막으로 받은 가격입니다"] = "The latest refresh failed; this is the last received price",
        ["현재가가 없어 매입금액으로 계산했습니다"] = "No price, so the cost is used",
        ["매입가"] = "at cost",
        ["삭제할까요?"] = "Delete?",
        ["{0} 삭제 확인"] = "Confirm deleting {0}",
        ["{0} 수정"] = "Edit {0}",
        ["{0} 삭제"] = "Delete {0}",
        ["{0} 순으로 정렬"] = "Sort by {0}",
        ["보유 종목이 없습니다."] = "No holdings.",

        // 보유 종목 화면
        ["삼성증권 잔고 화면의 수량과 평균매입단가를 옮겨 적습니다. 현재가는 자동으로 갱신됩니다."] =
            "Copy the quantity and average cost from your brokerage balance screen. Prices update automatically.",
        ["종목 추가"] = "Add holding",
        ["종목 수정"] = "Edit holding",
        ["보유 종목이 없습니다. 오른쪽에서 종목을 검색해 추가하세요."] = "No holdings yet. Search for a stock on the right to add one.",
        ["열 제목을 누르면 정렬됩니다."] = "Click a column header to sort.",
        ["예수금"] = "Cash",
        ["총 보유금액에 포함"] = "Include in total",
        ["{0}을(를) 삭제했습니다."] = "Deleted {0}.",
        ["{0}을(를) 수정했습니다."] = "Updated {0}.",
        ["{0}을(를) 추가했습니다."] = "Added {0}.",
        ["{0}을(를) 삭제할까요?"] = "Delete {0}?",
        ["예수금 {0}을 저장했습니다."] = "Saved cash of {0}.",
        ["예수금을 총 보유금액에 포함합니다."] = "Cash is now included in the total.",
        ["예수금을 총 보유금액에서 뺍니다."] = "Cash is now excluded from the total.",
        ["이미 보유 중인 종목을 고르면 기존 행을 수정합니다."] = "Picking a stock you already hold edits the existing row.",
        ["종목 검색"] = "Stock search",
        ["종목명 또는 종목코드"] = "Name or code",
        ["검색 결과"] = "Search results",
        ["검색 결과가 없습니다."] = "No results.",
        ["보유 중"] = "Held",
        ["보유 중 · 수정"] = "Held · edit",
        ["신규"] = "New",
        ["수량 (주)"] = "Quantity (shares)",
        ["평균매입단가 (원)"] = "Average cost (KRW)",
        ["현재가 {0} 기준 평가금액"] = "Value at the current price of {0}",
        ["저장하면 현재가를 조회해 평가금액을 계산합니다."] = "After saving, the price is fetched and the value is calculated.",
        ["삭제 확인"] = "Confirm delete",
        ["종목을 검색해 선택하세요."] = "Search for and select a stock.",
        ["수량은 1주 이상이어야 합니다."] = "Quantity must be at least 1 share.",
        ["평균매입단가는 0원보다 커야 합니다."] = "Average cost must be greater than 0.",
        ["종목코드가 비어 있습니다."] = "The stock code is empty.",
        ["수량은 1 이상이어야 합니다."] = "Quantity must be at least 1.",
        ["평균매입단가는 0보다 커야 합니다."] = "Average cost must be greater than 0.",
        ["이 계좌에 없는 그룹입니다."] = "That group does not belong to this account.",
        ["예수금은 0 이상이어야 합니다."] = "Cash cannot be negative.",

        // 오늘 등락 (F-14)
        ["오늘"] = "Today",
        ["오늘 손익"] = "Today's P/L",
        [" · 전일 종가 대비"] = " · vs. previous close",
        ["전일 대비 {0}"] = "{0} vs. previous close",

        // 종목 검색·종목 정보 (F-15)
        ["종목을 검색해 현재가와 시세 정보를 봅니다. 보유하지 않은 종목도 볼 수 있습니다."] =
            "Search for a stock to see its price and market data. Stocks you do not hold can be viewed too.",
        ["새로 고침"] = "Refresh",
        ["{0} 기준 · 전일 대비"] = "as of {0} · vs. previous close",
        ["전일 종가"] = "Previous close",
        ["시가"] = "Open",
        ["고가"] = "High",
        ["저가"] = "Low",
        ["거래량"] = "Volume",
        ["시가총액"] = "Market cap",
        ["상한가"] = "Upper limit",
        ["하한가"] = "Lower limit",
        ["52주 최고"] = "52-week high",
        ["52주 최저"] = "52-week low",
        ["화면을 열 때와 '새로 고침'을 누를 때 조회합니다. ETF처럼 PER·PBR·EPS가 없는 종목은 '-'로 표시합니다."] =
            "Data is fetched when the screen opens and when you click 'Refresh'. Stocks without PER, PBR or EPS, such as ETFs, show '-'.",
        ["KIS 앱키가 설정되지 않아 종목 정보를 받아올 수 없습니다."] = "Stock data is unavailable because no KIS app key is set.",
        ["종목 정보를 받아오지 못했습니다. 종목코드를 확인하거나 잠시 뒤 '새로 고침'을 눌러 주세요."] =
            "Could not load the stock data. Check the stock code, or click 'Refresh' in a moment.",
        ["내 보유 현황"] = "My position",
        ["보유하지 않은 종목입니다."] = "You do not hold this stock.",
        ["보유 종목에 추가하기"] = "Add it to Holdings",

        // 리밸런싱·추가매수
        ["추가매수"] = "Buy only",
        ["추가매수 계산"] = "Buy plan",
        ["리밸런싱 계산"] = "Rebalance plan",
        ["계산 방식"] = "Method",
        ["새 돈을 넣지 않고, 목표보다 많은 그룹을 팔아 부족한 그룹을 삽니다."] =
            "Without adding money, sell groups above target and buy groups below target.",
        ["매도 없이 매수만으로 목표 비중에 가깝게 배분합니다."] = "Allocate new money by buying only, moving toward the target weights.",
        ["{0} 시세 기준이며"] = "Based on prices as of {0};",
        ["수수료·세금은 제외합니다."] = "fees and taxes are not included.",
        ["보유 종목이 있어야 계산할 수 있습니다"] = "Holdings are needed to calculate",
        ["추가매수 배분과 리밸런싱은 지금 보유한 종목과 그룹별 목표 비중을 기준으로 계산합니다."] =
            "The buy plan and rebalance plan are calculated from your current holdings and each group's target weight.",
        ["그룹 목표 비중 합계가 100%가 아니어서 계산할 수 없습니다."] = "The group target weights do not add up to 100%, so nothing can be calculated.",
        ["그룹 관리에서 조정하기"] = "Adjust in Groups",
        ["미분류 종목이 있습니다. 미분류는 목표 0%로 계산되어 전부 매도 대상이 됩니다."] =
            "Some holdings are unclassified. Unclassified has a 0% target, so all of it is marked to sell.",
        ["미분류 종목이 있습니다. 미분류는 목표 0%로 계산되어 매수 배정을 받지 않습니다."] =
            "Some holdings are unclassified. Unclassified has a 0% target, so it gets no buy allocation.",
        ["매매 합계"] = "Trade totals",
        ["이미 목표 비중과 같습니다. 옮길 금액이 없습니다."] = "Already at the target weights. Nothing to move.",
        ["매도 합계"] = "Total to sell",
        ["매수 합계"] = "Total to buy",
        ["남는 금액"] = "Left over",
        ["그룹 비중 변화"] = "Group weight change",
        ["조정 후"] = "After",
        ["매수 후"] = "After buy",
        ["그룹별 조정 금액"] = "Adjustment by group",
        ["현재 금액"] = "Current value",
        ["조정 금액"] = "Adjustment",
        ["이 그룹에 보유 종목이 없어 살 종목을 정할 수 없습니다"] = "This group has no holdings, so there is nothing to buy",
        ["이 그룹 종목의 현재가가 없어 주수를 계산할 수 없습니다"] = "No prices for this group's holdings, so shares cannot be calculated",
        ["이 그룹에 보유 종목이 없어 배정 금액이 남습니다"] = "This group has no holdings, so its allocation is left over",
        ["종목 없음"] = "No holdings",
        ["조정 금액은 '보유 종목 평가금액 합계 × 목표 비중'에서 현재 금액을 뺀 값입니다. 매도 금액의 합과 매수 금액의 합은 같습니다. 예수금은 계산에 넣지 않습니다."] =
            "Adjustment = total holdings value × target weight − current value. Total sells equal total buys. Cash is not included.",
        ["종목별 매도·매수 수량"] = "Shares to sell and buy",
        ["매도·매수 금액을 그룹 안 종목의 현재 평가금액 비율로 나눠 1주 단위로 맞춥니다. 그래서 실제 합계는 조정 금액과 조금 다를 수 있고, 판 돈 중 사지 못한 금액이 남습니다. 매도에는 세금과 수수료가 붙을 수 있습니다."] =
            "Each group's amount is split across its holdings in proportion to their current value and rounded to whole shares, so the actual totals can differ slightly from the adjustment and some sale proceeds are left over. Selling may incur taxes and fees.",
        ["그룹 목표 비중 합계를 100%로 맞추면 계산됩니다."] = "Set the group target weights to total 100% to calculate.",
        ["매도하거나 매수할 종목이 없습니다."] = "Nothing to sell or buy.",
        ["종목의 현재가가 없어 주수를 계산할 수 없습니다. 그룹별 조정 금액까지만 계산했습니다."] =
            "Prices are missing, so shares cannot be calculated. Only the adjustment by group is shown.",
        ["조정 금액이 1주 가격보다 작아 매매할 종목이 없습니다."] = "The adjustment is smaller than the price of one share, so there is nothing to trade.",
        ["투입 금액"] = "Amount to invest",
        ["+100만"] = "+1M",
        ["+500만"] = "+5M",
        ["+1,000만"] = "+10M",
        ["지우기"] = "Clear",
        ["실제 매수 합계"] = "Actual buy total",
        ["그룹별 매수금액"] = "Buy amount by group",
        ["매수금액"] = "Buy amount",
        ["목표보다 비중이 높은 그룹에는 배정하지 않고, 부족한 그룹끼리는 매수 후 목표 비율이 같아지도록 나눕니다."] =
            "Groups above target get nothing; groups below target are filled so they reach the same proportion of their targets.",
        ["종목별 매수 수량"] = "Shares to buy",
        ["매수 주수"] = "Shares",
        ["그룹 배정 금액을 그룹 안 종목의 현재 평가금액 비율로 나눈 뒤, 1주 단위로 내림하고 남는 금액으로 가장 덜 채워진 종목을 1주씩 더 삽니다."] =
            "Each group's allocation is split across its holdings in proportion to their current value, rounded down to whole shares, and the remainder buys one more share of the least-filled holding at a time.",
        ["투입 금액을 입력하면 종목별 매수 수량이 표시됩니다."] = "Enter an amount to see how many shares to buy.",
        ["배정된 그룹 종목의 현재가가 없어 매수 주수를 계산할 수 없습니다. 그룹별 배정 금액까지만 계산했습니다."] =
            "Prices are missing for the allocated groups, so shares cannot be calculated. Only the allocation by group is shown.",
        ["투입 금액으로 살 수 있는 종목이 없습니다. 금액이 1주 가격보다 작거나, 배정된 그룹에 보유 종목이 없습니다."] =
            "Nothing can be bought with this amount. It is smaller than the price of one share, or the allocated groups have no holdings.",

        // 그룹 관리
        ["그룹별 목표 비중을 정합니다. 합계가 100%여야 저장되고, 추가매수 계산에 바로 반영됩니다."] =
            "Set the target weight of each group. They must total 100% to save, and the plans update right away.",
        ["미분류 종목"] = "Unclassified holdings",
        ["모든 종목에 그룹이 지정되어 있습니다."] = "Every holding has a group.",
        ["<a href=\"holdings\">보유 종목</a>에서 그룹을 지정하세요."] = "Assign groups in <a href=\"holdings\">Holdings</a>.",
        ["그룹 삭제 시"] = "When you delete a group",
        ["소속 종목은 미분류로 옮겨지고, 목표 비중은 다른 그룹에 다시 나눠 입력해야 합니다."] =
            "Its holdings become unclassified, and you need to redistribute its target weight to other groups.",
        ["그룹과 목표 비중"] = "Groups and target weights",
        ["그룹 추가"] = "Add group",
        ["새 그룹 이름"] = "New group name",
        ["예: 금, 현금성 자산"] = "e.g. Gold, Cash equivalents",
        ["새 그룹은 목표 비중 0%로 추가됩니다. 추가한 뒤 목표 비중을 다시 나눠 저장하세요."] =
            "A new group starts with a 0% target. After adding it, redistribute the targets and save.",
        ["종목 수"] = "Holdings",
        ["현재 비중"] = "Current",
        ["목표 비중"] = "Target",
        ["{0} 목표 비중"] = "Target weight of {0}",
        ["{0} 편집"] = "Edit {0}",
        ["소속 종목은 미분류로 옮겨집니다. 삭제할까요?"] = "Its holdings will become unclassified. Delete?",
        ["그룹 삭제"] = "Delete group",
        ["이름·색상 저장"] = "Save name and color",
        ["되돌리기"] = "Reset",
        ["저장했습니다 · 추가매수 계산에 반영됩니다"] = "Saved · the plans now use these targets",
        ["합계 100% · 저장할 수 있습니다"] = "Total 100% · ready to save",
        ["합계가 100%가 되도록 조정하세요 (현재 {0})"] = "Adjust so the total is 100% (now {0})",
        ["그룹 이름은 1~50자여야 합니다."] = "A group name must be 1–50 characters.",
        ["'미분류'는 그룹 이름으로 쓸 수 없습니다."] = "That name is reserved for holdings without a group.",
        ["같은 이름의 그룹이 이미 있습니다."] = "A group with that name already exists.",
        ["그룹을 찾을 수 없습니다."] = "Group not found.",
        ["목표 비중은 0% 이상이어야 합니다."] = "Target weights cannot be negative.",
        ["목표 비중 합계가 100%가 아닙니다."] = "The target weights do not total 100%.",
        ["모든 그룹의 목표 비중을 함께 저장해야 합니다."] = "The targets of all groups must be saved together.",

        // 설정·계좌 관리
        ["변경하면 바로 적용됩니다."] = "Changes apply immediately.",
        ["언어 (Language)"] = "Language",
        ["고른 언어는 이 브라우저에서 계속 유지됩니다. 계좌·그룹 이름과 종목명은 입력된 그대로 표시합니다."] =
            "Your choice is remembered in this browser. Account names, group names and stock names are shown as entered.",
        ["화면 모드"] = "Appearance",
        ["시스템 설정 따르기"] = "Match system",
        ["밝게"] = "Light",
        ["어둡게"] = "Dark",
        ["'시스템 설정 따르기'는 Windows나 휴대폰의 밝게·어둡게 설정을 따릅니다. 고른 모드는 이 브라우저에서 계속 유지됩니다."] =
            "'Match system' follows the light or dark setting of Windows or your phone. Your choice is remembered in this browser.",
        ["시세 갱신"] = "Price refresh",
        ["장중 시세 폴링 주기 (초)"] = "Refresh interval during market hours (seconds)",
        ["{0}~{1}초. 장중(평일 09:00~15:30)에만 이 주기로 조회하고, 다음 조회부터 적용됩니다."] =
            "{0}–{1} seconds. Used only during market hours (weekdays 09:00–15:30 KST) and applied from the next refresh.",
        ["{0}~{1} 사이의 숫자를 입력하세요."] = "Enter a number between {0} and {1}.",
        ["{0}초로 저장했습니다."] = "Saved as {0} seconds.",
        ["폴링 주기는 10~3600초여야 합니다."] = "The interval must be 10–3600 seconds.",
        ["총 보유금액에 예수금 포함"] = "Include cash in the total",
        ["포함하면 대시보드에 '현금' 항목이 따로 표시됩니다. 예수금 금액은 보유 종목 화면에서 입력합니다."] =
            "When included, the dashboard shows a separate 'Cash' item. Enter the cash amount on the Holdings screen.",
        ["계정"] = "Login",
        ["아이디"] = "User name",
        ["로그아웃"] = "Sign out",
        ["비밀번호를 바꾸면 다른 기기는 모두 다시 로그인해야 합니다. 비밀번호를 잊었으면 앱을 실행하는 PC에서 <code>scripts\\set-password.cmd</code>로 다시 정합니다."] =
            "Changing the password signs out all other devices. If you forget it, reset it with <code>scripts\\set-password.cmd</code> on the PC that runs the app.",
        ["보는 중"] = "Viewing",
        ["이름 변경"] = "Rename",
        ["계좌 이름"] = "Account name",
        ["{0} 위로"] = "Move {0} up",
        ["{0} 아래로"] = "Move {0} down",
        ["<strong>{0}</strong> 계좌를 삭제할까요?"] = "Delete the account <strong>{0}</strong>?",
        ["보유 종목 {0}개와 그룹·예수금이 함께 지워지고 되돌릴 수 없습니다."] =
            "Its {0} holding(s), groups and cash are deleted with it and cannot be restored.",
        ["이 계좌의 그룹·예수금도 함께 지워집니다."] = "Its groups and cash are deleted with it.",
        ["마지막 남은 계좌는 삭제할 수 없습니다"] = "The last remaining account cannot be deleted",
        ["마지막 남은 계좌는 삭제할 수 없습니다."] = "The last remaining account cannot be deleted.",
        ["새 계좌 이름"] = "New account name",
        ["새 계좌 이름 (예: 연금저축)"] = "New account name (e.g. Pension)",
        ["계좌 추가"] = "Add account",
        ["{0} 계좌를 추가했습니다. '보기'를 누르면 그 계좌로 바뀝니다."] = "Added the account {0}. Click 'View' to switch to it.",
        ["계좌 이름을 바꿨습니다."] = "Account renamed.",
        ["계좌를 삭제했습니다."] = "Account deleted.",
        ["보유 종목·그룹·목표 비중·예수금은 계좌마다 따로 관리합니다. 상단의 계좌 선택에서 볼 계좌를 바꿉니다. 새 계좌는 주식 50 / 채권 30 / 배당 20 그룹으로 시작합니다. 계좌번호는 저장하지 않습니다."] =
            "Holdings, groups, target weights and cash are kept separately for each account. Switch accounts with the selector at the top. A new account starts with three groups at 50 / 30 / 20. Account numbers are never stored.",
        ["계좌 이름은 1~50자여야 합니다."] = "An account name must be 1–50 characters.",
        ["같은 이름의 계좌가 이미 있습니다."] = "An account with that name already exists.",
        ["계좌를 찾을 수 없습니다."] = "Account not found.",

        // 로그인·가입·비밀번호
        ["로그인"] = "Sign in",
        ["비밀번호"] = "Password",
        ["한 번 로그인하면 이 기기에서 90일 동안 유지됩니다."] = "You stay signed in on this device for 90 days.",
        ["아이디 또는 비밀번호가 맞지 않습니다."] = "The user name or password is incorrect.",
        ["여러 번 틀려서 잠시 막았습니다. {0}초 뒤에 다시 시도하세요."] = "Too many failed attempts. Try again in {0} seconds.",
        ["가입"] = "Sign up",
        ["처음 사용합니다. 로그인에 쓸 계정을 만드세요."] = "First time here. Create the account you will sign in with.",
        ["비밀번호 ({0}자 이상)"] = "Password (at least {0} characters)",
        ["비밀번호 확인"] = "Confirm password",
        ["가입하고 시작하기"] = "Sign up and start",
        ["계정은 하나만 만들 수 있습니다. 가입한 뒤에는 다른 PC와 휴대폰에서도 같은 아이디로 로그인합니다."] =
            "Only one account can be created. After signing up, use the same user name on other PCs and phones.",
        ["비밀번호와 비밀번호 확인이 서로 다릅니다."] = "The password and its confirmation do not match.",
        ["아이디는 3~30자여야 합니다."] = "The user name must be 3–30 characters.",
        ["아이디에는 공백을 쓸 수 없습니다."] = "The user name cannot contain spaces.",
        ["비밀번호는 8자 이상이어야 합니다."] = "The password must be at least 8 characters.",
        ["이미 계정이 있습니다. 로그인하세요."] = "An account already exists. Please sign in.",
        ["아직 계정이 없습니다. 앱을 켜고 웹 화면에서 가입하세요."] = "No account yet. Start the app and sign up on the web screen.",
        ["비밀번호 변경"] = "Change password",
        ["비밀번호를 바꿨습니다. 이 기기는 로그인 상태가 유지되고, 다른 기기는 새 비밀번호로 다시 로그인해야 합니다."] =
            "Password changed. This device stays signed in; other devices must sign in again with the new password.",
        ["설정으로 돌아가기"] = "Back to Settings",
        ["현재 비밀번호"] = "Current password",
        ["새 비밀번호 ({0}자 이상)"] = "New password (at least {0} characters)",
        ["새 비밀번호 확인"] = "Confirm new password",
        ["새 비밀번호와 확인이 서로 다릅니다."] = "The new password and its confirmation do not match.",
        ["현재 비밀번호가 맞지 않습니다."] = "The current password is incorrect.",

        // 오류·연결
        ["오류"] = "Error",
        ["처리 중 오류가 발생했습니다"] = "Something went wrong",
        ["처리 중 오류가 발생했습니다."] = "Something went wrong.",
        ["새로고침"] = "Reload",
        ["잠시 후 다시 시도하세요."] = "Please try again in a moment.",
        ["대시보드로 이동"] = "Go to the dashboard",
        ["요청 ID"] = "Request ID",
        ["찾을 수 없음"] = "Not found",
        ["페이지를 찾을 수 없습니다"] = "Page not found",
        ["주소가 바뀌었거나 없는 화면입니다."] = "The address has changed or the page does not exist.",
        ["서버에 다시 연결하는 중입니다…"] = "Reconnecting to the server…",
        ["연결하지 못했습니다. 다시 시도하기까지 남은 시간(초):"] = "Could not connect. Seconds until the next attempt:",
        ["다시 연결하지 못했습니다."] = "Could not reconnect.",
        ["PC의 포트폴리오 앱이 켜져 있는지 확인한 뒤 다시 시도하세요."] = "Check that the Portfolio app is running on the PC, then try again.",
        ["다시 시도"] = "Retry",
        ["화면을 오래 쓰지 않아 연결을 잠시 멈췄습니다."] = "The connection was paused because the screen was idle.",
        ["다시 이어 가지 못했습니다."] = "Could not resume.",
        ["다시 시도하거나 페이지를 새로 여세요."] = "Retry or reload the page.",
        ["이어서 보기"] = "Resume",
    };
}
