// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Portfolio.Data;

#nullable disable

namespace Portfolio.Data.Migrations
{
    [DbContext(typeof(PortfolioDbContext))]
    [Migration("20261002085729_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Portfolio.Data.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("Portfolio.Data.AssetGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TargetWeight")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AssetGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#23395B",
                            Name = "주식",
                            SortOrder = 1,
                            TargetWeight = 0.5m
                        },
                        new
                        {
                            Id = 2,
                            Color = "#E08A2E",
                            Name = "채권",
                            SortOrder = 2,
                            TargetWeight = 0.3m
                        },
                        new
                        {
                            Id = 3,
                            Color = "#6BB3A8",
                            Name = "배당",
                            SortOrder = 3,
                            TargetWeight = 0.2m
                        });
                });

            modelBuilder.Entity("Portfolio.Data.CashBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CashBalances");
                });

            modelBuilder.Entity("Portfolio.Data.Holding", b =>
                {
                    b.Property<string>("SymbolCode")
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AvgPrice")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SymbolName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("SymbolCode");

                    b.HasIndex("GroupId");

                    b.ToTable("Holdings");
                });

            modelBuilder.Entity("Portfolio.Data.PriceCache", b =>
                {
                    b.Property<string>("SymbolCode")
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrevClose")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("SymbolCode");

                    b.ToTable("PriceCaches");
                });

            modelBuilder.Entity("Portfolio.Data.SymbolMaster", b =>
                {
                    b.Property<string>("SymbolCode")
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.Property<string>("Market")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SymbolName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("SymbolCode");

                    b.ToTable("SymbolMasters");
                });

            modelBuilder.Entity("Portfolio.Data.Holding", b =>
                {
                    b.HasOne("Portfolio.Data.AssetGroup", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Group");
                });
#pragma warning restore 612, 618
        }
    }
}
